name: Create release
on:
  workflow_dispatch:
  # Allows you to run this workflow manually from the Actions tab
#  push:
#    tags:
#      - v*
concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    name: Create release
    permissions:
      contents: write
      discussions: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      - uses: gradle/actions/setup-gradle@v3

      - name: Prepare keystore
        run: echo ${{ secrets.android_keystore_base64 }} | base64 -d >$GITHUB_WORKSPACE/keystore.jks

      - name: Build signed package
        # this actually is not signed
        # Make sure that caches are disabled to generate reproducible release builds
        # run: ./gradlew assembleWebRelease
        run: ./gradlew --no-build-cache --no-configuration-cache --no-daemon app:assembleRelease
        env:
          ANDROID_KEYSTORE: ${{ github.workspace }}/keystore.jks
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.android_keystore_password }}
          ANDROID_KEY_ALIAS: ${{ secrets.android_key_alias }}
          ANDROID_KEY_PASSWORD: ${{ secrets.android_key_password }}
      - name: Sign APK
        run: |
          apt-get install zipalign
          zipalign -v -p 4 app/build/outputs/apk/release/app-release-unsigned.apk app/build/outputs/apk/release/app-release-unsigned-aligned.apk
          # apksigner sign --ks my-release-key.jks --out signed-app-release.apk app/build/outputs/apk/release/app-release-unsigned-aligned.apk
      - name: Create Github release
        uses: softprops/action-gh-release@v2
        with:
          prerelease: ${{ env.prerelease }}
          files: app/build/outputs/apk/release/*.apk
          # app/build/outputs/apk/release/app-release-unsigned.apk
          fail_on_unmatched_files: true
          generate_release_notes: true
          discussion_category_name: Announcements

